spring:
  application:
    name: QFC2024


attachments:
  basePath: attachments
  questions:
    one:
      folder: Question 1
      files: access.log
    two:
      folder: Question 2
      files: StringUtils.java