spring:
  application:
    name: QFC2024


attachments:
  basePath: attachments
  questions:
    one:
      folder: Question 1
      file: access.log
    two:
      folder: Question 2
      file: StringUtils.java
      output: validLineCount.txt